export const PHRASES: Record<string, string> = {
  'iniciar sesión': 'تسجيل الدخول',
  'ingresando…': 'جارٍ الدخول…',
  'cerrar sesión': 'تسجيل الخروج',
  'bienvenido de nuevo': 'مرحبا بعودتك',
  'ingresa tus credenciales para continuar.': 'أدخل بيانات الاعتماد للمتابعة.',
  'correo electrónico': 'البريد الإلكتروني',
  'acceso de administrador:': 'دخول المسؤول:',
  'olvidaste tu contraseña? contacta al administrador del sistema.':
    'نسيت كلمة المرور؟ تواصل مع مسؤول النظام.',
  'buscar módulo…': 'ابحث عن وحدة…',
  'buscar en el sistema…': 'ابحث في النظام…',
  buscar: 'بحث',
  notificaciones: 'الإشعارات',
  'no tienes notificaciones.': 'لا توجد إشعارات.',
  'cargando notificaciones…': 'جارٍ تحميل الإشعارات…',
  'marcar todas como leídas': 'تعليم الكل كمقروء',
  'modo oscuro': 'الوضع الداكن',
  'modo claro': 'الوضع الفاتح',
  'cambiar a inglés': 'التبديل إلى الإنجليزية',
  'switch to spanish': 'التبديل إلى الإسبانية',
  módulos: 'الوحدات',
  hola: 'مرحبا',
  invitado: 'ضيف',
  'página no encontrada': 'الصفحة غير موجودة',
  'sin datos': 'لا توجد بيانات',
  'error al cargar': 'خطأ في التحميل',
  'operación exitosa': 'عملية ناجحة',
  cargando: 'جارٍ التحميل',
  'cargando…': 'جارٍ التحميل…',
  'guardando…': 'جارٍ الحفظ…',
  'ventas del mes': 'مبيعات الشهر',
  ingresos: 'الإيرادات',
  'ticket promedio': 'متوسط الفاتورة',
  'vs. mes anterior': 'مقابل الشهر الماضي',
  'últimos 12 meses': 'آخر 12 شهرًا',
  'sin ventas registradas': 'لا توجد مبيعات مسجلة',
  'registrar venta': 'تسجيل بيع',
  'evolución de ventas': 'تطور المبيعات',
  'top productos': 'أفضل المنتجات',
  'accesos rápidos': 'وصول سريع',
  'ver analytics': 'عرض التحليلات',
  'ver reportes': 'عرض التقارير',
  'conectado a la api real': 'متصل بواجهة API الحقيقية',
  productos: 'المنتجات',
  producto: 'منتج',
  categorías: 'الفئات',
  categoría: 'الفئة',
  clientes: 'العملاء',
  cliente: 'عميل',
  ventas: 'المبيعات',
  venta: 'بيع',
  inventario: 'المخزون',
  reportes: 'التقارير',
  reporte: 'تقرير',
  configuración: 'الإعدادات',
  cotizaciones: 'عروض الأسعار',
  cotización: 'عرض سعر',
  compras: 'المشتريات',
  devoluciones: 'المرتجعات',
  precios: 'الأسعار',
  precio: 'سعر',
  automatizaciones: 'الأتمتة',
  probabilidad: 'الاحتمالية',
  analytics: 'التحليلات',
  vendedores: 'البائعون',
  dashboard: 'لوحة القيادة',
  guardar: 'حفظ',
  'guardar cambios': 'حفظ التغييرات',
  cancelar: 'إلغاء',
  eliminar: 'حذف',
  editar: 'تحرير',
  crear: 'إنشاء',
  nuevo: 'جديد',
  nueva: 'جديدة',
  mostrando: 'إظهار',
  página: 'صفحة',
  anterior: 'السابق',
  siguiente: 'التالي',
  usuario: 'مستخدم',
  'productos destacados': 'منتجات مميزة',
  'envíos a todo el perú': 'شحن إلى كل أنحاء البيرو',
  'compra 100% segura': 'شراء آمن 100٪',
  'compra segura': 'شراء آمن',
  'garantía oficial + boleta/factura': 'ضمان رسمي وإيصال/فاتورة',
  'garantía oficial y boleta/factura': 'ضمان رسمي وإيصال/فاتورة',
  'precios al por mayor': 'أسعار الجملة',
  'catálogo mayorista': 'كتالوج الجملة',
  'explora nuestras categorias': 'استكشف فئاتنا',
  'explorar categorías': 'تصفح الفئات',
  'marcas distribuidoras': 'علامات تجارية موزعة',
  'atención personalizada para mayoristas': 'خدمة مخصصة لأصحاب الجملة',
  'atención vía whatsapp y llamadas': 'خدمة عبر واتساب والمكالمات',
  'asesoría especializada': 'استشارات متخصصة',
  'todo para campaña en un solo lugar': 'كل شيء للموسم في مكان واحد',
  'horario de atención': 'ساعات العمل',
  'lunes a sábado: 8:00 - 18:00': 'الاثنين إلى السبت: ٨:٠٠ - ١٨:٠٠',
  'consultas y cotizaciones': 'استفسارات وعروض أسعار',
  'envío y garantía': 'الشحن والضمان',
  inicio: 'الرئيسية',
  catálogo: 'الكتالوج',
  contacto: 'اتصل بنا',
  cotizar: 'اطلب عرض سعر',
  'ver catálogo': 'عرض الكتالوج',
  'cargando productos...': 'جارٍ تحميل المنتجات...',
  'no se encontraron productos': 'لم يتم العثور على منتجات',
  'no se encontraron resultados': 'لا توجد نتائج',
  'sin stock': 'نفذ المخزون',
  agotado: 'نفذ',
  'añadir a cotización': 'أضف إلى عرض السعر',
  'cotizar por whatsapp': 'اطلب عرض سعر عبر واتساب',
  cantidad: 'الكمية',
  'subtotal estimado': 'المجموع الفرعي التقديري',
  'tu cotización está vacía': 'عرض أسعارك فارغ',
  'generar cotización en salesia': 'أنشئ عرض أسعار في SalesIA',
  'enviar cotización': 'إرسال عرض الأسعار',
  'datos enviados': 'تم إرسال البيانات',
  'mensaje enviado': 'تم إرسال الرسالة',
  descripción: 'الوصف',
  especificaciones: 'المواصفات',
  marca: 'العلامة التجارية',
  filtros: 'عوامل التصفية',
  'rango de precio': 'نطاق السعر',
  'solo disponibles': 'المتاح فقط',
  'más vendido': 'الأكثر مبيعًا',
  'enviando a salesia.': 'جارٍ الإرسال إلى SalesIA.',
  'no se pudo enviar el mensaje.': 'تعذر إرسال الرسالة.',
  'error al cargar producto': 'خطأ في تحميل المنتج',
  'producto no encontrado': 'المنتج غير موجود',
  'zapallal, puente piedra, lima 15122': 'زابالال، بوينتي بييدرا، ليما ١٥١٢٢',
  'todos los derechos reservados': 'جميع الحقوق محفوظة',
  'política de privacidad': 'سياسة الخصوصية',
  'términos y condiciones': 'الشروط والأحكام',
  'acerca de nosotros': 'من نحن',
  whatsapp: 'واتساب',
  teléfono: 'الهاتف',
  dirección: 'العنوان',
  envíos: 'الشحنات',
  garantía: 'ضمان',
  stock: 'المخزون',
  proveedores: 'الموردون',
  unidad: 'الوحدة',
  impuestos: 'الضرائب',
  descuento: 'الخصم',
  'método de pago': 'طريقة الدفع',
  pendiente: 'معلق',
  completada: 'مكتملة',
  cancelada: 'ملغاة',
  aprobada: 'معتمدة',
  borrador: 'مسودة',
  convertida: 'محوّلة',
  cerrar: 'إغلاق',
  añadir: 'إضافة',
  agregar: 'إضافة',
  nombre: 'الاسم',
  estado: 'الحالة',
  activo: 'نشط',
  inactivo: 'غير نشط',
  total: 'الإجمالي',
  fecha: 'التاريخ',
  acciones: 'الإجراءات',
  detalles: 'التفاصيل',
  resumen: 'الملخص',
  idioma: 'اللغة',
  tema: 'المظهر',
  error: 'خطأ',
  éxito: 'نجاح',
  confirmar: 'تأكيد',
  'ver detalle': 'عرض التفاصيل',
  'configuración general': 'الإعدادات العامة',
  'sign in': 'تسجيل الدخول',
  'sign out': 'تسجيل الخروج',
  'dark mode': 'الوضع الداكن',
  'light mode': 'الوضع الفاتح',
  'no data': 'لا توجد بيانات',
  search: 'بحث',
  save: 'حفظ',
  cancel: 'إلغاء',
  delete: 'حذف',
  edit: 'تحرير',
  create: 'إنشاء',
  loading: 'جارٍ التحميل',
  settings: 'الإعدادات',
  reports: 'التقارير',
  customers: 'العملاء',
  inventory: 'المخزون',
  notifications: 'الإشعارات',
}
