export const WORDS: Record<string, string> = {
  el: 'الـ',
  la: 'الـ',
  los: 'الـ',
  las: 'الـ',
  un: 'واحد',
  una: 'واحدة',
  y: 'و',
  o: 'أو',
  de: 'من',
  del: 'من ال',
  en: 'في',
  con: 'مع',
  por: 'بواسطة',
  para: 'لأجل',
  sin: 'بدون',
  sobre: 'حول',
  todos: 'كل',
  todas: 'كل',
  más: 'أكثر',
  menos: 'أقل',
  aquí: 'هنا',
  ahora: 'الآن',
  hoy: 'اليوم',
  si: 'إذا',
  no: 'لا',
  sí: 'نعم',
  sistema: 'نظام',
  módulo: 'وحدة',
  módulos: 'وحدات',
  panel: 'لوحة',
  menú: 'قائمة',
  principal: 'رئيسي',
  general: 'عام',
  bienvenido: 'مرحبا',
  bienvenida: 'مرحبا',
  perfil: 'الملف الشخصي',
  cuenta: 'الحساب',
  sesión: 'الجلسة',
  contraseña: 'كلمة المرور',
  correo: 'البريد',
  email: 'البريد',
  teléfonos: 'الهواتف',
  direcciones: 'العناوين',
  'buscar…': 'بحث…',
  resultados: 'النتائج',
  ninguno: 'لا شيء',
  ninguna: 'لا شيء',
  seleccionar: 'اختيار',
  selecciona: 'اختر',
  seleccione: 'اختر',
  aplicar: 'تطبيق',
  filtrar: 'تصفية',
  ordenar: 'ترتيب',
  descargar: 'تنزيل',
  exportar: 'تصدير',
  importar: 'استيراد',
  imprimir: 'طباعة',
  actualizar: 'تحديث',
  recargar: 'إعادة تحميل',
  restaurar: 'استعادة',
  reintentar: 'إعادة المحاولة',
  continuar: 'متابعة',
  siguiente: 'التالي',
  anterior: 'السابق',
  primero: 'الأول',
  último: 'الأخير',
  volver: 'رجوع',
  regresar: 'رجوع',
  entendido: 'مفهوم',
  aceptar: 'قبول',
  rechazar: 'رفض',
  guardado: 'تم الحفظ',
  guardada: 'تم الحفظ',
  añadido: 'تمت الإضافة',
  agregado: 'تمت الإضافة',
  eliminado: 'تم الحذف',
  editado: 'تم التعديل',
  creado: 'تم الإنشاء',
  enviado: 'تم الإرسال',
  recibido: 'تم الاستلام',
  pendientes: 'معلقة',
  completados: 'مكتملة',
  activos: 'نشطة',
  inactivos: 'غير نشطة',
  disponible: 'متاح',
  disponibles: 'متاح',
  agotados: 'نافد',
  resumen: 'الملخص',
  'resumen general': 'نظرة عامة',
  estadísticas: 'الإحصائيات',
  estadistica: 'الإحصائيات',
  gráfico: 'رسم بياني',
  gráficos: 'رسوم بيانية',
  tendencia: 'الاتجاه',
  comparativa: 'مقارنة',
  promedio: 'المتوسط',
  variación: 'التغير',
  crecimiento: 'النمو',
  rendimiento: 'الأداء',
  métricas: 'المقاييس',
  indicadores: 'المؤشرات',
  criterios: 'المعايير',
  período: 'الفترة',
  rango: 'النطاق',
  desde: 'من',
  hasta: 'إلى',
  registrados: 'مسجلة',
  registradas: 'مسجلة',
  generados: 'مولدة',
  generadas: 'مولدة',
  recientes: 'حديثة',
  últimos: 'آخر',
  próximos: 'القادمة',
  'ventas netas': 'صافي المبيعات',
  costo: 'التكلفة',
  costos: 'التكاليف',
  utilidad: 'الربح',
  utilidades: 'الأرباح',
  margen: 'هامش',
  ganancia: 'ربح',
  ganancias: 'أرباح',
  facturación: 'الفواتير',
  factura: 'فاتورة',
  boleta: 'إيصال',
  nota: 'ملاحظة',
  notas: 'ملاحظات',
  observación: 'ملاحظة',
  observaciones: 'ملاحظات',
  detalles: 'التفاصيل',
  detalle: 'التفصيل',
  'resumen de venta': 'ملخص البيع',
  número: 'الرقم',
  código: 'الرمز',
  referencia: 'المرجع',
  'cantidad total': 'الكمية الإجمالية',
  descuentos: 'الخصومات',
  impuesto: 'ضريبة',
  'total a pagar': 'الإجمالي المطلوب',
  'forma de pago': 'طريقة الدفع',
  efectivo: 'نقدا',
  tarjeta: 'بطاقة',
  crédito: 'آجل',
  transferencia: 'تحويل',
  pago: 'الدفع',
  pagos: 'المدفوعات',
  cobros: 'التحصيلات',
  deudas: 'الديون',
  saldo: 'الرصيد',
  'stock mínimo': 'حد المخزون الأدنى',
  existencias: 'المخزون',
  almacén: 'المستودع',
  almacenes: 'المستودعات',
  entrada: 'إدخال',
  salida: 'إخراج',
  movimientos: 'الحركات',
  traspaso: 'نقل',
  lote: 'دفعة',
  proveedor: 'المورد',
  pedido: 'طلب',
  pedidos: 'الطلبات',
  'orden de compra': 'أمر الشراء',
  recepción: 'الاستلام',
  entrega: 'التسليم',
  envío: 'الشحن',
  courier: 'الناقل',
  guía: 'دليل',
  seguimiento: 'التتبع',
  devolución: 'المرتجع',
  reembolso: 'استرداد',
  garantías: 'الضمانات',
  reclamos: 'الشكاوى',
  incidencias: 'الحوادث',
  soporte: 'الدعم',
  ayuda: 'المساعدة',
  preguntas: 'الأسئلة',
  respuesta: 'الإجابة',
  respuestas: 'الإجابات',
  comentario: 'تعليق',
  comentarios: 'تعليقات',
  historial: 'السجل',
  actividad: 'النشاط',
  actividades: 'الأنشطة',
  tareas: 'المهام',
  tarea: 'مهمة',
  evento: 'حدث',
  eventos: 'الأحداث',
  calendario: 'التقويم',
  recordatorio: 'تذكير',
  automática: 'تلقائية',
  automático: 'تلقائي',
  automatización: 'أتمتة',
  regla: 'قاعدة',
  reglas: 'القواعد',
  flujo: 'تدفق',
  disparador: 'المشغّل',
  condición: 'شرط',
  acción: 'إجراء',
  'acciones masivas': 'إجراءات مجمعة',
  permisos: 'الأذونات',
  roles: 'الأدوار',
  acceso: 'دخول',
  accesos: 'الصلاحيات',
  autorización: 'التفويض',
  sesiones: 'الجلسات',
  dispositivos: 'الأجهزة',
  seguridad: 'الأمان',
  respaldo: 'النسخ الاحتياطي',
  copia: 'نسخة',
  restauración: 'الاستعادة',
  archivo: 'ملف',
  archivos: 'الملفات',
  carpeta: 'مجلد',
  documento: 'وثيقة',
  documentos: 'الوثائق',
  imagen: 'صورة',
  imágenes: 'الصور',
  adjunto: 'مرفق',
  versión: 'إصدار',
  tamaño: 'الحجم',
  tipo: 'النوع',
  formato: 'التنسيق',
  idiomas: 'اللغات',
  moneda: 'العملة',
  'zona horaria': 'المنطقة الزمنية',
  preferencias: 'التفضيلات',
  'notificaciones push': 'الإشعارات الفورية',
  'correo electrónico': 'البريد الإلكتروني',
  mensaje: 'رسالة',
  mensajes: 'الرسائل',
  plantilla: 'نموذج',
  plantillas: 'النماذج',
  campaña: 'حملة',
  campañas: 'الحملات',
  promoción: 'عرض ترويجي',
  cupón: 'قسيمة',
  'código de descuento': 'كود الخصم',
  'lista de precios': 'قائمة الأسعار',
  mayorista: 'بالجملة',
  'cliente potencial': 'عميل محتمل',
  oportunidad: 'فرصة',
  etapa: 'مرحلة',
  etapas: 'المراحل',
  embudo: 'قمع',
  conversión: 'التحويل',
  interacción: 'تفاعل',
  interacciones: 'التفاعلات',
  segmento: 'شريحة',
  puntuación: 'التقييم',
  clasificación: 'التصنيف',
  prioridad: 'الأولوية',
  urgencia: 'الاستعجال',
  vencimiento: 'الاستحقاق',
  'fecha límite': 'الموعد النهائي',
  aprobación: 'الموافقة',
  aprobado: 'معتمد',
  rechazado: 'مرفوض',
  'en proceso': 'قيد التنفيذ',
  'en revisión': 'قيد المراجعة',
  finalizado: 'منتهي',
  finalizada: 'منتهية',
  'activo:': 'نشط:',
  'usuario activo': 'مستخدم نشط',
  'invitado:': 'ضيف:',
  'nombre de usuario': 'اسم المستخدم',
  rol: 'دور',
  equipo: 'فريق',
  equipos: 'الفِرق',
  departamento: 'القسم',
  sucursal: 'الفرع',
  empresa: 'الشركة',
  organización: 'المؤسسة',
  empleados: 'الموظفين',
  trabajador: 'عامل',
  jefe: 'المدير',
  gerente: 'مدير',
  vendedor: 'بائع',
  analista: 'محلل',
  'cliente nuevo': 'عميل جديد',
  'nuevo cliente': 'عميل جديد',
  datos: 'البيانات',
  dato: 'بيان',
  información: 'المعلومة',
  campos: 'الحقول',
  campo: 'حقل',
  tabla: 'جدول',
  columna: 'عمود',
  fila: 'صف',
  índice: 'الفهرس',
  'resumen de datos': 'ملخص البيانات',
  calidad: 'الجودة',
  completitud: 'الاكتمال',
  actualizado: 'محدّث',
  actualizada: 'محدّثة',
  sincronizado: 'متزامن',
  conectado: 'متصل',
  desconectado: 'غير متصل',
  'en línea': 'عبر الإنترنت',
  'fuera de línea': 'غير متصل',
  servidor: 'الخادم',
  'base de datos': 'قاعدة البيانات',
  api: 'واجهة البرمجة',
  'estado del sistema': 'حالة النظام',
  salud: 'الصحة',
  uptime: 'وقت التشغيل',
  latencia: 'زمن الاستجابة',
  errores: 'الأخطاء',
  advertencias: 'التحذيرات',
  registros: 'السجلات',
  log: 'سجل',
  auditoría: 'التدقيق',
  trazabilidad: 'التتبع',
  privacidad: 'الخصوصية',
  términos: 'الشروط',
  legal: 'قانوني',
  copyright: 'حقوق النشر',
  'contacto:': 'اتصل بنا:',
  'whatsapp:': 'واتساب:',
  horario: 'الدوام',
  días: 'الأيام',
  hamburguesa: 'برغر',
  'abrir menú': 'فتح القائمة',
  'cerrar menú': 'إغلاق القائمة',
  'ir al inicio': 'الذهاب للرئيسية',
  'página principal': 'الصفحة الرئيسية',
  'siguiente página': 'الصفحة التالية',
  'anterior página': 'الصفحة السابقة',
  'de {a} a {b} de {c}': 'من {a} إلى {b} من {c}',
  'sin resultados': 'لا توجد نتائج',
  todo: 'كل',
  vacío: 'فارغ',
  vacía: 'فارغة',
  añade: 'أضف',
  agrega: 'أضف',
  quitar: 'إزالة',
  seleccionado: 'محدد',
  seleccionada: 'محددة',
  ver: 'عرض',
  'ver todos': 'عرض الكل',
  'ver más': 'عرض المزيد',
  'ver menos': 'عرض أقل',
  abrir: 'فتح',
  duplicar: 'نسخ',
  mover: 'نقل',
  compartir: 'مشاركة',
  copiar: 'نسخ',
  pegar: 'الصق',
  'descargar todo': 'تنزيل الكل',
  subir: 'رفع',
  cargar: 'تحميل',
  'buscar productos': 'بحث عن المنتجات',
  'añadir producto': 'إضافة منتج',
  'nueva venta': 'بيع جديد',
  'nueva categoría': 'فئة جديدة',
  'nuevo reporte': 'تقرير جديد',
  'guardar como': 'حفظ باسم',
  cambiar: 'تغيير',
  renombrar: 'إعادة تسمية',
  confirmación: 'تأكيد',
  '¿estás seguro?': 'هل أنت متأكد؟',
  'esta acción no se puede deshacer.': 'لا يمكن التراجع عن هذا الإجراء.',
  requerido: 'مطلوب',
  opcional: 'اختياري',
  inválido: 'غير صالح',
  válido: 'صالح',
  'error de conexión': 'خطأ في الاتصال',
  'sin conexión': 'لا يوجد اتصال',
  'intenta de nuevo': 'حاول مرة أخرى',
  'cargando datos…': 'جارٍ تحميل البيانات…',
  'guardando cambios…': 'جارٍ حفظ التغييرات…',
  operando: 'يعمل',
  procesando: 'جارٍ المعالجة',
  completado: 'مكتمل',
  fallido: 'فشل',
  fallida: 'فشلت',
  exitoso: 'ناجح',
  exitosa: 'ناجحة',
  informe: 'تقرير',
  informes: 'التقارير',
  cuadro: 'جدول',
  'cuadro de mando': 'لوحة القيادة',
  análisis: 'تحليل',
  analizar: 'تحليل',
  pronóstico: 'توقعات',
  predicción: 'تنبؤ',
  modelo: 'نموذج',
  algoritmo: 'خوارزمية',
  inteligencia: 'ذكاء',
  ia: 'الذكاء الاصطناعي',
  'automático:': 'تلقائي:',
  sugerencia: 'اقتراح',
  sugerencias: 'الاقتراحات',
  recomendación: 'توصية',
  recomendaciones: 'التوصيات',
  insight: 'بصيرة',
  descubre: 'اكتشف',
  aprende: 'تعلم',
  mejora: 'حسّن',
  optimiza: 'حسّن',
  maximiza: 'ضخّم',
}
